#ifndef STRINGS
#define STRINGS
#include <string>

using std::string;

static const string DATABASE_NAME = "fiszka.db";
static const string TABLE_QUESTIONS = "Questions";
static const string TABLE_TAGS  = "Tags";
static const string TABLE_QUESTIONS_TAGS  = "Questions_tags";
static const string COLUMN_ID  = "Id";
static const string COLUMN_VALUE = "Value";
static const string COLUMN_ANSWER = "Answer";
static const string COLUMN_TAG  = "Tag";
static const string COLUMN_QUESTION_ID = "Question_id";
static const string COLUMN_TAG_ID = "Tag_id";
static const string CREATE_TABLE_IF_NOT_EXISTS  = "create table if not exists";
static const string INTEGER_NOT_NULL = "INTEGER NOT NULL";
static const string PRIMARY_KEY  = "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL";
static const string TEXT = "TEXT NOT NULL";
static const string FOREIGN_KEY = "FOREIGN KEY ";
static const string REFERENCES = "REFERENCES ";
static const string SELECT = "SELECT ";
static const string FROM = "FROM ";
static const string WHERE = "WHERE ";
static const string INSERT = "INSERT INTO ";
static const string VALUES = "VALUES";
static const string UPDATE = "UPDATE ";
static const string SET = "SET ";
static const string DELETE = "DELETE FROM ";
static const string INNER_JOIN = "INNER JOIN ";
static const string ON = "ON ";
static const string AND = "AND ";
static const string LIMIT  = "LIMIT ";

static const char ANSWER_YES_LARGE = 'Y';
static const char ANSWER_YES_SMALL = 'y';

static const char *TAG_LIST = "Tags list";
static const char *ADD_TAG = "Add tag";
static const char *ADD_QUESTION = "Add question";
static const char *REMOVE_TAG = "Remove the tag";
static const char *MAKE_SERIES = "Make questions series";
static const char *QUESTIONS_MENU = "Questions menu";
static const char *TAGS_MENU = "Tags menu";
static const string MAIN_MENU = "MAIN MENU";
static const string SELECTED_TAG = "Selected tag";
static const string CHOSE_NUMBER = "Chose number";
static const string WRONG_VALUE = "Wrong value";
static const string WRONG_VALUE_TRY_AGAIN = "Wrong value. Try again.";
static const string SELECT_TAG_FIRST = "Select the tag first";
static const string TAGS_LIST = "Tags list";
static const string TAG_CREATED_CORRECTLY = "The tag created correctly"; 
static const string DATABASE_ERROR = "Database error";
static const string INFO_CREATING_QUESTION = "Add a question. First, the query, and then after pressing the ENTER key, the answer. Then confirm by pressing the ENTER key.";  
static const string QUESTION_CREATED_CORRECTLY = "The question created correctly";
static const string CHOSE_TAG = "Choose the tag from the list";
static const string ADD_THE_TAG = "Add the tag";
static const string TO_THE_QUESTION = "to the question";
static const string TAG_ADDED_SUCCESFULLY = "The tag added succesfully";
static const char *INFO_CONFIRM_REMOVE = "Confirm deletion by typing (Y)";
static const string THE_TAG = "The tag";
static const string SUCCESFULLY_REMOVED = "has been succesfuly removed from database";
static const string QUESTIONS_LIST_TO_REMOVED = "List of the questions to removed"; 
static const string CHOOSE_QUESTION = "Choose one question";
static const string NO_QUESTIONS_TO_REMOVE = "There are no questions to remove";
static const string QUESTIONS_SUCCESFULLY_REMOVED = "The question has been succesfully deleted";
static const string INFO_QUESTIONS_NUMBER_IN_SERIES = "Enter number of questions you want to do in series. The number must be less than";
static const char* VALUE = "Value";
static const char* ANSWER = "Answer";
static const char *LIST_OF_TAGS_FROM_DATABASE = "List of tags from databse" ;
static const char *RANDOM_QUESTION_LIST = "Random question list";
static const char *PLEASE_SELECT_OPTION = "Please select option";
static const char *CREATE = "Create";
static const char *SELECT_QUESTION = "Select question";
static const char *UPDATE_QUESTION = "Update selected question";
static const char *REMOVE_QUESTION = "Remove selected question";
static const char *ADD_TAG_TO_QUESTION = "Add tag to selected question";
static const char *REMOVE_TAG_FROM_QUESTION = "Remove tag from selected question";
static const char *EXIT = "Exit";
static const char *QUESTION_MENU = "QUESTION MENU";
static const char *INFO_SELECT_QUESTION = "To select question, choose number";
static const char *INFO_FIRST_SELECT_QUESTION = "Select question first";
static const char *INFO_SELECTED_QUESTION = "Currently selected question";
static const char *INFO_ARE_YOU_SURE_TO_REMOVE_QUESTION = "Are you sure do you want to remove selected question? If yes push (Y).";
static const char *INFO_SELECT_TAG_TO_REMOVE_FROM_QUESTION= "Select tag from the list below to remove it from the quesiton.\n";
static const char *TAG_HAS_BEEN_REMOVED = "Tag has been removed";
static const char *LIST_OF_QUESTIONS = "List of questions";
static const char *LIST_OF_TAGS = "List of tags";
static const char *NO_TAGS = "No tags";
static const char *NO_QUESTIONS = "No questions";

static const char *TAG_MENU = "TAG MENU";
static const char *SELECT_TAG = "Select tag";
static const char *SET_NEW_TAG = "Set new tag";
static const char *UPDATE_TAG = "Update selected tag";
static const char *REMOVE_SELECTED_TAG = "Remove selected tag";
static const char *ADD_QUESTION_TO_TAG = "Add question to selected tag";
static const char *REMOVE_QUESTION_FROM_TAG = "Remove question from selected tag";
static const char *CURRENTLY_SELECTED_TAG = "Currently selected tag";
static const char *INFO_SELECT_TAG_TO_ADD_QUESTION = "Select tag from the list below to add the question";
static const char *TAG_UPDATE_SUCCESFULLY = "Tag updated succesfully";
static const char *SELECT_QUESTION_TO_REMOVE_FROM_TAG = "Select the qestion to remove from below list available questios";
static const char *EMPTY_LIST_RELATED_QUESTIONS_WITH_TAG = "I have nothing to do here, the list of connected questions with a tag is empty.";
static const char *REMOVED_RELATION_QUESTION_AND_TAG_SUCCESFULLY = "Removing relation of the question with the tag has been succesfully finished";
#endif
