CFLAGS=-Wall -g 
TARGET=main
TARGET_T=tests
ALL_CPP_FILE=/*.cpp
MODELS_PATH=Models$(ALL_CPP_FILE)
DATABASE_PATH=Database$(ALL_CPP_FILE)
TESTS_PATH=Tests$(ALL_CPP_FILE)
VIEWS_PATH=Views$(ALL_CPP_FILE)
CONTROLLERS_PATH=Controllers$(ALL_CPP_FILE)
CONSTANTS_PATH=Constants/*.h
ALL_PATHS=$(CONSTANTS_PATH) $(DATABASE_PATH) $(VIEWS_PATH) $(MODELS_PATH) $(CONTROLLERS_PATH) -lsqlite3

fiszka: 	
	rm -f $(TARGET)
	g++ -o $(TARGET) $(TARGET).cpp $(ALL_PATHS)
	./$(TARGET)

ftests:
	rm -f $(TARGET_T)
	g++ -o $(TARGET_T) $(TESTS_PATH)/*.cpp $(ALL_PATHS) 
	./$(TARGET_T)
